### ISSUE TITLE
Pressing Start on the Taskbar causes a Crash

### ISSUE THREAD

**Issue by feren** [StartNine/Start9#6]
Version: Just pulled it off of this Repo

Pretty much self-explanatory, clicked Start on New Taskbar = Crash

**Comment by Reflectronic** [comment]
oh :b:rap

**Comment by Reflectronic** [comment]
Hmmm works for me. I'll implement some sort of a crash logging soon:tm: so we can look into exactly what is causing this

**Comment by feren** [comment]
If it helps, it was in Safe Mode when this happened

**Comment by feren** [comment]
UPDATE 2: It does it on Normal Windows 7 Boot:
`InstalledTransientModules[0].HandleCommand(command);`
............................................ ^ System.ArgumentOutOfRangeException

**Comment by feren** [comment]
"Index was out of range. Must be non-negative and less than the size of collection."
File: IModule.cs

**Comment by Reflectronic** [comment]
Hmmm... do you have *both* of the modules installed in `%appdata%\Start9\Modules`?

**Comment by feren** [comment]
Oh... that might be the issue. :man_facepalming:

**Comment by feren** [comment]
Erm, is that Start9/Modules/*, or module files in the Modules folder?

**Comment by feren** [comment]
...with them as Modules/TestFixedModule and Modules/TestTransientModule, it still throws an exception

**Comment by Reflectronic** [comment]
![image](https://user-images.githubusercontent.com/27514983/34471127-ec95f4d4-ef0d-11e7-8674-bd62afa3702a.png)
So you have these files?

**Comment by feren** [comment]
TestFixed: Yes
TestTransient: No

**Comment by Reflectronic** [comment]
Ahh that's the problem. The start button *is* TestTransient

**Comment by feren** [comment]
Can I have a copy of TestTransient over Discord DMs?

**Comment by Reflectronic** [comment]
Sure

**Comment by feren** [comment]
Fixed over TeamViewer (so others would have to ask Reflectron about how he fixed my one)...

**Comment by Reflectronic** [comment]
Alright, we looked into the issue and it seems like it's a simple fix:

Firstly, feren did not have the TestTransientModule [this is the Start Menu]. Thus the `InstalledTransientModules` collection was empty.

This fixed that issue - however, another issue cropped up. Code Access Security (CAS) policy does **not** trust assemblies downloaded from the internet, and when they are loaded `NotSupportedException` is thrown. To remedy this, an `app.exe.config` file must be included with the following contents:
```xml
<configuration>  
   <runtime>  
      <loadFromRemoteSources enabled="true"/>  
   </runtime>  
</configuration>
```
This allows assemblies from remote sources (downloaded from the net, etc.) to be loaded. I will update the build settings for the Start9 project to include an `app.exe.config` enabling `loadFromRemoteSources` in a future commit.
