### ISSUE TITLE
[SUGGESTION] Modules that allow for Explorer Tweaks, ala Classic Shell's Explorer Tweaks

### ISSUE THREAD

**Issue by feren** [startnine/start9#7]
Please Note: Don't rush yourselves to do this, I'd rather have a complete Shell Replacement before you people start working on Modular Explorer Tweaks, based on Classic Shell's Explorer Tweak-age.
Given you're going to potentially use some code from the now open source Classic Shell, here's an idea for Start9, given it's going Modular:
1. Classic Menu Module - What is says on the tin
2. Windows XP Style Menu Module - Classic Shell's XP Layout Menu
3. Windows 7 Style Menu Module - Menu that looks like the Windows 7 Menu, mainly doable with Classic Shell Code
4. (the one of this issue) File Explorer Tweaks as Modules that can be enabled

Now, 4 can be anything, as long as it brings more functionality to, or otherwise lets you customise, File Explorer... The main things I can think of is mainly Classic Shell Explorer Tweaks being a Module, at first, and then at least whatever other users come up with for Tweaks (Ribbon Skinning..?, Plexplorer Layout..?)...

**Comment by reflectronic** [comment]
Considering Start9 will be replacing Explorer, I no longer see the need for such a feature. Closing.
