### ISSUE TITLE
window controls are broken after closing

### ISSUE THREAD

**Issue by logonoff** [StartNine/Start9#9]
fresh windows 7 VM
commit version ``ea22090``
steps to reproduce:
* open a compiled build of start9
* close it
* open it again from the taskbar
* click maximise
* enjoy
![screengrab of the issue](https://i.imgur.com/XRcCi39.gif)
![screengrab 2](https://i.imgur.com/5mPOJv5.png)

**Comment by Splitwirez** [comment]
...WHAT BRANCH ARE YOU PULLING THIS FROM...!?  Q A Q

**Comment by logonoff** [comment]
master, ``ea22090``

**Comment by Splitwirez** [comment]
try pulling whatever's the latest from messages and see if it still happens

**Comment by logonoff** [comment]
fixed in messages, guess it was a glitched window state or something lol
